spring:
  mvc:
    async:
      request-timeout: 60000
  thymeleaf:
    excluded-view-names: text
    template-resolver-order: 100

server:
  undertow:
    worker-threads: 10

logging.level:
  showcase: DEBUG
  org.springframework:
    web: DEBUG
    boot: INFO
  io.undertow: WARN