spring:
  mvc:
    async:
      request-timeout: 60000
    contentnegotiation:
      favor-path-extension: true
      media-types.xml: application/xml
      media-types.json: application/json
    pathmatch:
      use-registered-suffix-pattern: true

server:
  undertow:
    worker-threads: 10

logging.level:
  showcase: DEBUG
  org.springframework:
    web: DEBUG
    boot: INFO