spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    async:
      request-timeout: 60000
  thymeleaf:
    excluded-view-names: text
    template-resolver-order: 100

server:
  undertow:
    threads:
      worker: 10

logging.level:
  showcase: DEBUG
  org.springframework:
    web: DEBUG
    boot: INFO
  io.undertow: WARN